import { createElement, useEffect, useId, useState } from 'react';
import { Platform, Pressable, View } from 'react-native';
import { space } from '@autodeck/ui/theme';
import { T } from './kit';

export type UploadFile = { blob: Blob; type: string };
const css = `autodeck-uploader input:focus-visible + span {outline:2px solid #EC8638;outline-offset:4px} .autodeck-control:focus-visible {outline:2px solid #EC8638;outline-offset:3px}`;
const control = {width:'100%',minWidth:0,minHeight:48,boxSizing:'border-box' as const,padding:'12px 44px 12px 16px',borderRadius:14,border:'1px solid #454548',background:'#202023',color:'#F6F4F1',fontSize:15,fontFamily:'Archivo,system-ui,sans-serif',colorScheme:'dark',appearance:'none' as const};
export function SelectField({label,value,onChange,options,placeholder}:{label:string;value:string;onChange:(v:string)=>void;options:Array<{value:string;label:string}>;placeholder?:string}) {
 if(Platform.OS!=='web')return <View><T tone="secondary">{label}</T>{options.map(o=><Pressable key={o.value} accessibilityRole="button" accessibilityState={{selected:value===o.value}} onPress={()=>onChange(o.value)} style={{paddingVertical:12}}><T tone={value===o.value?"accent":"secondary"}>{o.label}</T></Pressable>)}</View>;
 return createElement('div',{style:{position:'relative',width:'100%',minWidth:0}},createElement('style',null,css),createElement('select',{'aria-label':label,className:'autodeck-control',value,onChange:(e:{target:{value:string}})=>onChange(e.target.value),style:control},placeholder?createElement('option',{value:'',disabled:true},placeholder):null,...options.map(o=>createElement('option',{key:o.value,value:o.value},o.label))),createElement('span',{'aria-hidden':true,style:{position:'absolute',right:16,top:'50%',transform:'translateY(-50%)',pointerEvents:'none',color:'#b7b4b0',fontSize:18}},'⌄'));
}
export function DateField({label,value,onChange,min,max,error}:{label:string;value:string;onChange:(v:string)=>void;min?:string|undefined;max?:string|undefined;error?:string|undefined}) {
 return <View style={{gap:space.breath}}><T role="label" tone="tertiary">{label}</T>{Platform.OS==='web'?createElement('input',{'aria-label':label,type:'date',value,min,max,className:'autodeck-control',style:{...control,appearance:'auto',paddingRight:16},onChange:(e:{target:{value:string}})=>onChange(e.target.value)}):<T tone="secondary">Open AutoDeck on the web to choose this date.</T>}{error?<T role="caption" tone="danger">{error}</T>:null}</View>;
}
export function FileUploader({files,onChange,accept='image/jpeg,image/png,image/webp',multiple=false,maxFiles=1,label='Add image'}:{files:UploadFile[];onChange:(files:UploadFile[])=>void;accept?:string;multiple?:boolean;maxFiles?:number;label?:string}) {
 const id=useId();const [previews,setPreviews]=useState<string[]>([]); const [error,setError]=useState('');
 useEffect(()=>{if(Platform.OS!=='web')return;const urls=files.map(f=>f.type.startsWith('image/')?URL.createObjectURL(f.blob):'');setPreviews(urls);return ()=>urls.forEach(u=>{if(u)URL.revokeObjectURL(u);});},[files]);
 if(Platform.OS!=='web')return null;
 function select(list:ArrayLike<File>|null){const picked=Array.from(list??[]);const allowed=accept.split(',');if(picked.length>maxFiles){setError(`Add up to ${maxFiles} images.`);return;}if(picked.some(f=>!allowed.includes(f.type))){setError('Choose a supported file type.');return;}setError('');onChange(picked.map(f=>({blob:f,type:f.type})));}
 const input=createElement('input',{id,type:'file',accept,multiple,'aria-label':label,style:{position:'absolute',opacity:0,width:'100%',height:'100%',inset:0,cursor:'pointer'},onChange:(e:{target:{files:ArrayLike<File>|null}})=>select(e.target.files)});
 const trigger=createElement('label',{htmlFor:id,style:{display:'block',position:'relative',cursor:'pointer'}},input,createElement('span',{style:{display:'flex',alignItems:'center',gap:14,minHeight:80,padding:18,boxSizing:'border-box',border:'1px dashed rgba(236,134,56,.5)',borderRadius:18,background:'linear-gradient(145deg,rgba(236,134,56,.09),rgba(255,255,255,.03))',color:'#f6f4f1'}},createElement('span',{'aria-hidden':true,style:{fontSize:24,color:'#EC8638'}},'▧'),createElement('span',null,createElement('strong',null,label),createElement('span',{style:{display:'block',fontSize:12,color:'#aaa7a2',marginTop:6}},multiple?`Up to ${maxFiles} images. First image is the cover.`:'Choose an image or scan.'))));
 const grid=files.length?createElement('div',{style:{display:'grid',gridTemplateColumns:multiple?'repeat(3,minmax(0,1fr))':'minmax(0,1fr)',gap:10,marginTop:14}},...files.map((f,i)=>createElement('div',{key:i,style:{minWidth:0}},previews[i]?createElement('img',{src:previews[i],alt:multiple?`Selected image ${i+1}`:'Selected image',style:{width:'100%',height:multiple?95:180,objectFit:'cover',borderRadius:12}}):null,createElement('span',{style:{display:'block',color:'#cbc7c1',fontSize:12,overflowWrap:'anywhere',marginTop:6}},multiple&&i===0?'Cover':(f.blob as File).name??`Image ${i+1}`)))):null;
 return createElement('div',{style:{width:'100%'}},createElement('style',null,css),createElement('autodeck-uploader',null,trigger),grid,error?createElement('p',{role:'alert',style:{color:'#FF8D8D',fontSize:13}},error):null);
}
