import { createZodDto } from 'nestjs-zod';
import { z } from 'zod';

/**
 * No `customerId` field here — the document ID is always generated by
 * CustomersService, never accepted from the client.
 */
export const CreateCustomerSchema = z.object({
  name: z.string().min(1),
  phone: z.string().min(1),
  email: z.string().email(),
});

export class CreateCustomerDto extends createZodDto(CreateCustomerSchema) {}
