import { createZodDto } from 'nestjs-zod';
import { PackageDefinitionSchema } from '@autodeck/domain';

/**
 * Derived directly from the pre-existing `PackageDefinitionSchema`
 * (packages/domain/src/packages.ts, Phase 2A) via `.omit()`, rather than
 * re-declaring `name`/`includedServiceId`/`quantity`/`price`/
 * `validityDuration` from scratch — this is the first backend DTO that
 * reuses an existing domain Zod schema this literally, since it is
 * genuinely the same shape (every prior module's domain type was either
 * unused by the backend or only field-compatible, not identical).
 * `packageDefinitionId` is omitted: the document ID is always generated by
 * PackageDefinitionsService, never accepted from the client.
 */
export const CreatePackageDefinitionSchema = PackageDefinitionSchema.omit({ packageDefinitionId: true });

export class CreatePackageDefinitionDto extends createZodDto(CreatePackageDefinitionSchema) {}
