import { createZodDto } from 'nestjs-zod';
import { z } from 'zod';

/** No `inventoryItemId` field — the document ID is always generated by
 * InventoryService, never accepted from the client. `currentStock` here is
 * the initial stock at item creation only; every subsequent change goes
 * through the dedicated `restock`/usage-recording endpoints, never this
 * schema again (see update-inventory-item.dto.ts, which excludes it). */
export const CreateInventoryItemSchema = z.object({
  name: z.string().min(1),
  currentStock: z.number().int().nonnegative(),
  lowStockThreshold: z.number().int().nonnegative(),
});

export class CreateInventoryItemDto extends createZodDto(CreateInventoryItemSchema) {}
