import { createZodDto } from 'nestjs-zod';
import { z } from 'zod';

/**
 * `basePrice` uses the exact same constraint as the pre-existing
 * `ServiceSchema` in `packages/domain/src/types.ts`
 * (`z.number().int().nonnegative()`) — an integer number of paise, never a
 * floating-point rupee value. No `serviceId` field — the document ID is
 * always generated by ServicesService, never accepted from the client.
 */
export const CreateServiceSchema = z.object({
  name: z.string().min(1),
  basePrice: z.number().int().nonnegative(),
});

export class CreateServiceDto extends createZodDto(CreateServiceSchema) {}
